apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test-cert
  namespace: default
spec:
  dnsNames:
    - "nginx1.sentracam.net"
  secretName: nginx-test-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
